### ISSUE TITLE
Spigot - Config unable to be saved

### ISSUE THREAD

**Issue by kiranhart** [craftaro/SongodaCore#39]
When using the normal Spigot jar (1.18+) as I don't believe this issue happens on 1.17 or lower. The config is unable to be saved (this applies to any file that uses the config system btw) 

It's very easy to recreate, just start the server using the base spigot jar (1.18+) with any updated plugin using SongodaCore. You can still access the in-game editor, but since the config can't be saved, any changes made aren't applied and it just spams the console

**Comment by kiranhart** [comment]
Update, it seems to happen when you use subnodes, so like settings.autokill will cause the error.

**Comment by SpraxDev** [comment]
Is this still an issue?

**Comment by kiranhart** [comment]
> Is this still an issue?

Haven't ran into the issue since you did that recode

**Comment by SpraxDev** [comment]
The recode is not published yet but the issue relates to Spigot using a bugged version of the YAML library.
I believe PaperMC wasn't affected and newer Spigot versions should already be using a newer version of that library.

I'll be closing this ticket for now in that case - Thanks for reporting!
